global:
  cattle:
    url: https://10.7.2.98.nip.io/k8s/clusters/c-m-8ppsndgb/
    psp:
      enabled: false
neuvector:
  controller:
    pvc:
      enabled: false
    ranchersso:
      enabled: true
    runAsUser: 1000
    apisvc:
      type: ClusterIP
    ingress:
      enabled: true
      host: neuvector-controller.10.7.2.115.nip.io
    federation:
      managedsvc:
        type: ClusterIP
        ingress:
          enabled: true
          host: neuvector-fed-managed.10.7.2.115.nip.io
  k3s:
    enabled: true
    runtimePath: /run/k3s/containerd/containerd.sock
  manager:
    svc:
      type: ClusterIP
    ingress:
      enabled: true
      host: neuvector-manager.10.7.2.115.nip.io
    runAsUser: 5400
  enforcer:
    runAsUser: 1000
  cve:
    scanner:
      runAsUser: 5400
    updater:
      runAsUser: 1000
  rbac: true
  leastPrivilege: true
